In [1]:
import pandas as  pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')




from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MultiLabelBinarizer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from sklearn.ensemble import RandomForestClassifier

from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import time

In [2]:
file_path = r'A:\final year project\AyuCare\cbc_data.csv'    
df = pd.read_csv(file_path)


In [3]:
df

GENDER     WBC     NE#    LY#    MO#   EO#    BA#   RBC    HGB     MCV  \
0           1  106.32   93.10   6.01   1.72  1.67   3.82  4.27  12.40   89.20   
1           1   89.31    7.67  78.98   0.54  0.04   2.09  4.97  11.46   73.38   
2           1   85.73   75.17   4.55   4.34  0.20   1.46  4.99  14.68   94.09   
3           1   73.09    3.42  66.45   0.76  0.09   2.37  4.37  13.24   90.00   
4           1   60.87    3.23  54.05   1.67  0.30   1.61  3.62  10.89   91.69   
...       ...     ...     ...    ...    ...   ...    ...   ...    ...     ...   
29995       1   63.81  192.05   5.64   2.41  0.36  23.86  6.00  21.15   80.31   
29996       1  181.85    7.57  31.95  14.63  0.38   5.99  3.55  12.58   86.13   
29997       1   39.99  108.39  43.60  13.82  1.32   3.14  6.56   6.68  100.99   
29998       1  210.38   71.17  83.07   6.39  2.89  16.94  1.35  15.10   96.96   
29999       1  162.72  140.50  25.22  11.25  7.10   1.47  6.42   9.13   99.93   

          MCH    MCHC      PLT  \
0       29.00   32.50   240000   
1       23.08   31.46    75990   
2       29.42   31.27   160900   
3       30.31   33.68   116700   
4       30.06   32.78   125500   
...       ...     ...      ...   
29995   12.59   25.62  1509470   
29996   81.15   25.54   810300   
29997   63.55  109.67  1196390   
29998  112.56  156.23  1446260   
29999   20.24   93.06  1587080   

                                                 Disease  
0      ['Infection/Inflammation', 'Possible Leukemia'...  
1      ['Infection/Inflammation', 'Bacterial Infectio...  
2      ['Infection/Inflammation', 'Bacterial Infectio...  
3      ['Infection/Inflammation', 'Viral Infection', ...  
4      ['Infection/Inflammation', 'Viral Infection', ...  
...                                                  ...  
29995  ['Infection/Inflammation', 'Bacterial Infectio...  
29996  ['Infection/Inflammation', 'Possible Leukemia'...  
29997  ['Infection/Inflammation', 'Bacterial Infectio...  
29998  ['Infection/Inflammation', 'Possible Leukemia'...  
29999  ['Infection/Inflammation', 'Possible Leukemia'...  

[30000 rows x 14 columns]

In [4]:
df.shape

(30000, 14)

In [5]:
df.describe()

GENDER           WBC           NE#           LY#           MO#  \
count  30000.000000  30000.000000  30000.000000  30000.000000  30000.000000   
mean       0.393267     64.741016     50.717203     23.097595      4.832011   
std        0.488483     76.447472     61.355523     27.946269      5.741358   
min        0.000000      0.570000      0.030000      0.110000      0.000000   
25%        0.000000      7.299500      4.280000      2.060000      0.510000   
50%        0.000000     12.445000      9.125000      3.520000      0.930000   
75%        1.000000    121.065000     96.345000     44.080000      9.102500   
max        1.000000    246.700000    197.200000     89.600000     18.510000   

                EO#           BA#           RBC           HGB          MCV  \
count  30000.000000  30000.000000  30000.000000  30000.000000  30000.00000   
mean       2.393830      6.096100      4.450508     12.786489     85.44792   
std        2.976138      7.904098      1.447098      4.192183     16.30078   
min        0.000000      0.000000      0.870000      2.990000     49.93000   
25%        0.110000      0.050000      3.777500     10.500000     76.61750   
50%        0.380000      0.140000      4.620000     12.820000     84.80000   
75%        4.630000     12.122500      5.280000     15.100000     92.40000   
max        9.410000     24.730000      7.500000     22.450000    125.30000   

                MCH          MCHC           PLT  
count  30000.000000  30000.000000  3.000000e+04  
mean      51.324792     62.603998  5.664475e+05  
std       35.580016     42.903386  4.798782e+05  
min       12.550000     18.070000  1.300000e+04  
25%       27.180000     32.500000  2.240000e+05  
50%       30.190000     34.600000  3.196850e+05  
75%       74.642500     92.685000  8.719625e+05  
max      139.000000    168.000000  1.770000e+06

In [6]:
df.isnull().sum()

GENDER     0
WBC        0
NE#        0
LY#        0
MO#        0
EO#        0
BA#        0
RBC        0
HGB        0
MCV        0
MCH        0
MCHC       0
PLT        0
Disease    0
dtype: int64

In [7]:
df.Disease.value_counts()

Disease
[]                                                                                                                                                                                                                                                                                                                  2868
['Iron Deficiency']                                                                                                                                                                                                                                                                                                 2030
['Infection/Inflammation', 'Possible Leukemia', 'Bacterial Infection or Stress', 'Viral Infection', 'Chronic Inflammation or Infection Recovery', 'Allergy or Parasitic Infection', 'Allergic Reaction or Inflammation', 'Anemia', 'Anemia or Fluid Overload', 'Thrombocytosis (Inflammation, Iron Deficiency)']    1189
['Anemia', 'Anemia or Fluid Overload', 'Iron Deficien

In [8]:
from sklearn.preprocessing import LabelEncoder
X = df.drop(columns=['Disease'],axis=1)
y = df['Disease']

le=LabelEncoder()
le.fit(y)
y=le.transform(y)

In [9]:
y

array([1071,  579,  685, ...,  716, 1038, 1013])

In [10]:
X

GENDER     WBC     NE#    LY#    MO#   EO#    BA#   RBC    HGB     MCV  \
0           1  106.32   93.10   6.01   1.72  1.67   3.82  4.27  12.40   89.20   
1           1   89.31    7.67  78.98   0.54  0.04   2.09  4.97  11.46   73.38   
2           1   85.73   75.17   4.55   4.34  0.20   1.46  4.99  14.68   94.09   
3           1   73.09    3.42  66.45   0.76  0.09   2.37  4.37  13.24   90.00   
4           1   60.87    3.23  54.05   1.67  0.30   1.61  3.62  10.89   91.69   
...       ...     ...     ...    ...    ...   ...    ...   ...    ...     ...   
29995       1   63.81  192.05   5.64   2.41  0.36  23.86  6.00  21.15   80.31   
29996       1  181.85    7.57  31.95  14.63  0.38   5.99  3.55  12.58   86.13   
29997       1   39.99  108.39  43.60  13.82  1.32   3.14  6.56   6.68  100.99   
29998       1  210.38   71.17  83.07   6.39  2.89  16.94  1.35  15.10   96.96   
29999       1  162.72  140.50  25.22  11.25  7.10   1.47  6.42   9.13   99.93   

          MCH    MCHC      PLT  
0       29.00   32.50   240000  
1       23.08   31.46    75990  
2       29.42   31.27   160900  
3       30.31   33.68   116700  
4       30.06   32.78   125500  
...       ...     ...      ...  
29995   12.59   25.62  1509470  
29996   81.15   25.54   810300  
29997   63.55  109.67  1196390  
29998  112.56  156.23  1446260  
29999   20.24   93.06  1587080  

[30000 rows x 13 columns]

In [11]:
y[0]

np.int64(1071)

In [12]:
y[1]

np.int64(579)

In [13]:
y[247]

np.int64(556)

In [14]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [15]:
# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [16]:
X_train

array([[-0.80509039, -0.76303358, -0.06351944, ...,  0.60302294,
         0.45465706, -0.86889649],
       [ 1.24209656, -0.64962049, -0.69753976, ..., -0.59654682,
        -0.64574063, -0.56775257],
       [-0.80509039,  2.10905169,  0.04291122, ...,  2.08421614,
         2.03824146,  0.35799774],
       ...,
       [ 1.24209656, -0.70717731, -0.69085728, ..., -0.91976735,
        -0.72965149, -0.31143326],
       [-0.80509039, -0.3284796 , -0.16587542, ...,  0.59178048,
        -0.86577355,  2.13454058],
       [ 1.24209656,  1.69071827,  1.92036111, ...,  1.92625968,
         0.68168256, -0.00268312]])

In [17]:
X_test


array([[ 1.24209656, -0.74315032, -0.75621516, ..., -0.66962276,
        -0.67371092, -0.79281342],
       [-0.80509039,  1.28010269,  0.35600969, ...,  0.78627492,
         0.50686827,  2.17509321],
       [ 1.24209656,  2.02807971,  0.65117956, ...,  0.76294683,
         1.65341693, -0.1927345 ],
       ...,
       [-0.80509039,  0.67313987,  1.93177022, ..., -1.05355254,
         1.17932057,  1.36820838],
       [ 1.24209656,  1.69856692,  2.35195129, ..., -0.3975554 ,
         0.40873918, -0.19156752],
       [ 1.24209656,  0.54429108,  2.29409083, ...,  0.24579399,
         0.04885482,  2.35778844]])

In [18]:
#Logistic Regression
log_reg_model = OneVsRestClassifier(LogisticRegression(max_iter=300, solver='lbfgs'))
log_reg_model.fit(X_train, y_train)

y_pred_log_reg = log_reg_model.predict(X_test)
log_reg_accuracy = accuracy_score(y_test, y_pred_log_reg)


model_performance = {}
model_performance['Logistic Regression'] = log_reg_accuracy

print("Logistic Regression Accuracy:", log_reg_accuracy)

Logistic Regression Accuracy: 0.27066666666666667


In [19]:
# Decision Tree
dt_model = DecisionTreeClassifier(max_depth=20, random_state=42)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)
dt_accuracy = accuracy_score(y_test, y_pred_dt)
model_performance['Decision Tree'] = dt_accuracy



In [20]:
from sklearn.naive_bayes import GaussianNB

# Naive Bayes (GaussianNB)
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
y_pred_nb = nb_model.predict(X_test)
nb_accuracy = accuracy_score(y_test, y_pred_nb)
model_performance['Naive Bayes'] = nb_accuracy


In [21]:
rf_model = RandomForestClassifier(random_state=42, n_jobs=-1, n_estimators=10)  # Parallelize and use 100 trees
rf_model.fit(X_train, y_train)  # Train with the encoded labels

# Predict and calculate accuracy
y_pred_rf = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, y_pred_rf)
print(f"Random Forest Accuracy: {rf_accuracy:.4f}")
print("Model Performance Keys:", model_performance.keys())
model_performance['Random Forest'] = rf_accuracy
#print(f"Random Forest Accuracy: {rf_accuracy}")

Random Forest Accuracy: 0.4043
Model Performance Keys: dict_keys(['Logistic Regression', 'Decision Tree', 'Naive Bayes'])


In [22]:

print("Model Performance:")
for model_name, accuracy in model_performance.items():
    print(f"{model_name}: {accuracy:.4f}")

Model Performance:
Logistic Regression: 0.2707
Decision Tree: 0.3773
Naive Bayes: 0.2908
Random Forest: 0.4043


In [23]:
import pickle
pickle.dump(rf_model, open(r'A:\final year project\AyuCare\model\rf_model.pkl', 'wb'))


In [24]:
rf=pickle.load(open(r'A:\final year project\AyuCare\model\rf_model.pkl','rb'))

In [25]:
rf

RandomForestClassifier(n_estimators=10, n_jobs=-1, random_state=42)

In [26]:
rf.predict([[ 0	-0.8050903866715282,	-0.7630335831960053,	-0.06351943603928424,	0.5429224719457784,	2.0218532429890277,	1.3461193169397718	,1.583242979321215,	0.8358188278798898,	0.8762910503726755,	0.8780142946314983	,0.6030229377713175,	0.4546570635146985	,-0.8688964893557258]])


array([247])

In [27]:
y[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]

array([1071, 1071, 1071, 1071, 1071, 1071, 1071, 1071, 1071, 1071, 1071,
       1071, 1071, 1071, 1071,  579])

In [28]:
df['Disease'].iloc[247]


"['Infection/Inflammation', 'Bacterial Infection or Stress', 'Folate Deficiency']"